Repository uclaacm/TeachLAFrontend, pull requests merged in 2020-02, with the labels that each got.

#197 Added help text to loading page
  src/components/common/LoadingPage.js
  src/styles/Loading.scss
Labels: feature

#203 (very) minor code cleanup!
  src/components/Login.js
  src/components/Login/LoginForm.js
  src/components/Main.js
  src/components/Output/Output.js
  src/components/Output/Processing.js
  src/components/Sketches/index.js
  src/components/TextEditor/components/EditorRadio.js
  src/components/common/Footer.js
  src/components/common/ProfilePanel.js
  src/styles/Editor.scss
  src/styles/Panel.scss
  src/styles/Radio.scss
  src/styles/Switch.scss
  src/styles/variables.scss
Labels: refactor

#211 Tries Out GitHub Actions for CI
  .github/workflows/nodejs.yml
Labels: devops

#210 Adds Tests for <Loading>'s Timer + Minor Improvements
  src/components/common/LoadingPage.js
  src/components/common/LoadingPage.test.js
  src/components/common/__snapshots__/LoadingPage.test.js.snap
Labels: refactor

#199 Adds link to GitHub Repo on 404 page, makes styling respect current theme
  src/components/Error.js
  src/components/PageNotFound.js
  src/styles/Page.scss
Labels: feature
