Repository uclaacm/TeachLAFrontend, pull requests merged in 2020-05, with the labels that each got.

#149 Refactoring image selector components
  src/components/Sketches/components/CreateSketchModal.js
  src/components/Sketches/components/EditSketchModal.js
  src/components/common/ImageSelector.js
  src/components/common/ImageSelector.test.js
  src/components/common/ProfilePanel.js
  src/components/common/ProfilePanel.test.js
  src/constants/index.js
  src/styles/ImageSelector.scss
  src/styles/SketchesModal.scss
Labels: refactor

#281 Fix Incorrect State Update in Sketch/index.js, Typo in Image Selector
  src/components/Sketches/index.js
  src/components/common/ImageSelector.js
Labels: bug

#279 Add Share Sketch Button
  src/components/TextEditor/components/ShareSketchModal.js
  src/components/TextEditor/components/TextEditor.js
  src/lib/index.js
  src/lib/sketch.js
  src/lib/sketch.test.js
  src/styles/Modals.scss
Labels: feature

#282 Removing Unused helper.js + test
  src/lib/helpers.js
  src/lib/helpers.unit.test.js
  src/lib/index.js
Labels: refactor

#278 Add fork button
  src/components/EditorAndOutput/EditorAndOutput.js
  src/components/TextEditor/components/TextEditor.js
  src/components/TextEditor/containers/TextEditorContainer.js
  src/styles/Editor.scss
Labels: feature

#269 New Login Page Design & Unifying Login/CreateUser
  src/components/CreateUser.js
  src/components/CreateUser.test.js
  src/components/Login.js
  src/components/Login/CreateUserForm.js
  src/components/Login/CreateUserForm.test.js
  src/components/Login/LoginForm.js
  src/components/__snapshots__/CreateUser.test.js.snap
  src/components/app.js
  src/img/background1.svg
  src/img/login1.svg
  src/img/login2.svg
  src/img/login3.svg
  src/img/login4.svg
  src/img/login5.svg
  src/img/tla-logo-green.svg
  src/styles/Login.scss
  src/styles/global.scss
Labels: feature, refactor
